// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pingpong2/ent/read"
	"pingpong2/ent/sentense"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SentenseCreate is the builder for creating a Sentense entity.
type SentenseCreate struct {
	config
	mutation *SentenseMutation
	hooks    []Hook
}

// SetChinese sets the "chinese" field.
func (sc *SentenseCreate) SetChinese(s string) *SentenseCreate {
	sc.mutation.SetChinese(s)
	return sc
}

// SetPinyin sets the "pinyin" field.
func (sc *SentenseCreate) SetPinyin(s string) *SentenseCreate {
	sc.mutation.SetPinyin(s)
	return sc
}

// SetEnglish sets the "english" field.
func (sc *SentenseCreate) SetEnglish(s string) *SentenseCreate {
	sc.mutation.SetEnglish(s)
	return sc
}

// AddReadIDs adds the "reads" edge to the Read entity by IDs.
func (sc *SentenseCreate) AddReadIDs(ids ...int) *SentenseCreate {
	sc.mutation.AddReadIDs(ids...)
	return sc
}

// AddReads adds the "reads" edges to the Read entity.
func (sc *SentenseCreate) AddReads(r ...*Read) *SentenseCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sc.AddReadIDs(ids...)
}

// Mutation returns the SentenseMutation object of the builder.
func (sc *SentenseCreate) Mutation() *SentenseMutation {
	return sc.mutation
}

// Save creates the Sentense in the database.
func (sc *SentenseCreate) Save(ctx context.Context) (*Sentense, error) {
	var (
		err  error
		node *Sentense
	)
	if len(sc.hooks) == 0 {
		if err = sc.check(); err != nil {
			return nil, err
		}
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SentenseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sc.check(); err != nil {
				return nil, err
			}
			sc.mutation = mutation
			if node, err = sc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			if sc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SentenseCreate) SaveX(ctx context.Context) *Sentense {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SentenseCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SentenseCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SentenseCreate) check() error {
	if _, ok := sc.mutation.Chinese(); !ok {
		return &ValidationError{Name: "chinese", err: errors.New(`ent: missing required field "Sentense.chinese"`)}
	}
	if _, ok := sc.mutation.Pinyin(); !ok {
		return &ValidationError{Name: "pinyin", err: errors.New(`ent: missing required field "Sentense.pinyin"`)}
	}
	if _, ok := sc.mutation.English(); !ok {
		return &ValidationError{Name: "english", err: errors.New(`ent: missing required field "Sentense.english"`)}
	}
	return nil
}

func (sc *SentenseCreate) sqlSave(ctx context.Context) (*Sentense, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (sc *SentenseCreate) createSpec() (*Sentense, *sqlgraph.CreateSpec) {
	var (
		_node = &Sentense{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: sentense.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sentense.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Chinese(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sentense.FieldChinese,
		})
		_node.Chinese = value
	}
	if value, ok := sc.mutation.Pinyin(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sentense.FieldPinyin,
		})
		_node.Pinyin = value
	}
	if value, ok := sc.mutation.English(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sentense.FieldEnglish,
		})
		_node.English = value
	}
	if nodes := sc.mutation.ReadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sentense.ReadsTable,
			Columns: []string{sentense.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: read.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SentenseCreateBulk is the builder for creating many Sentense entities in bulk.
type SentenseCreateBulk struct {
	config
	builders []*SentenseCreate
}

// Save creates the Sentense entities in the database.
func (scb *SentenseCreateBulk) Save(ctx context.Context) ([]*Sentense, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Sentense, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SentenseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SentenseCreateBulk) SaveX(ctx context.Context) []*Sentense {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SentenseCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SentenseCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
