// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pingpong2/ent/predicate"
	"pingpong2/ent/read"
	"pingpong2/ent/sentense"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SentenseUpdate is the builder for updating Sentense entities.
type SentenseUpdate struct {
	config
	hooks    []Hook
	mutation *SentenseMutation
}

// Where appends a list predicates to the SentenseUpdate builder.
func (su *SentenseUpdate) Where(ps ...predicate.Sentense) *SentenseUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetChinese sets the "chinese" field.
func (su *SentenseUpdate) SetChinese(s string) *SentenseUpdate {
	su.mutation.SetChinese(s)
	return su
}

// SetPinyin sets the "pinyin" field.
func (su *SentenseUpdate) SetPinyin(s string) *SentenseUpdate {
	su.mutation.SetPinyin(s)
	return su
}

// SetEnglish sets the "english" field.
func (su *SentenseUpdate) SetEnglish(s string) *SentenseUpdate {
	su.mutation.SetEnglish(s)
	return su
}

// AddReadIDs adds the "reads" edge to the Read entity by IDs.
func (su *SentenseUpdate) AddReadIDs(ids ...int) *SentenseUpdate {
	su.mutation.AddReadIDs(ids...)
	return su
}

// AddReads adds the "reads" edges to the Read entity.
func (su *SentenseUpdate) AddReads(r ...*Read) *SentenseUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.AddReadIDs(ids...)
}

// Mutation returns the SentenseMutation object of the builder.
func (su *SentenseUpdate) Mutation() *SentenseMutation {
	return su.mutation
}

// ClearReads clears all "reads" edges to the Read entity.
func (su *SentenseUpdate) ClearReads() *SentenseUpdate {
	su.mutation.ClearReads()
	return su
}

// RemoveReadIDs removes the "reads" edge to Read entities by IDs.
func (su *SentenseUpdate) RemoveReadIDs(ids ...int) *SentenseUpdate {
	su.mutation.RemoveReadIDs(ids...)
	return su
}

// RemoveReads removes "reads" edges to Read entities.
func (su *SentenseUpdate) RemoveReads(r ...*Read) *SentenseUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.RemoveReadIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SentenseUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SentenseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SentenseUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SentenseUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SentenseUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SentenseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sentense.Table,
			Columns: sentense.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sentense.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Chinese(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sentense.FieldChinese,
		})
	}
	if value, ok := su.mutation.Pinyin(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sentense.FieldPinyin,
		})
	}
	if value, ok := su.mutation.English(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sentense.FieldEnglish,
		})
	}
	if su.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sentense.ReadsTable,
			Columns: []string{sentense.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: read.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedReadsIDs(); len(nodes) > 0 && !su.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sentense.ReadsTable,
			Columns: []string{sentense.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: read.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ReadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sentense.ReadsTable,
			Columns: []string{sentense.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: read.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sentense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// SentenseUpdateOne is the builder for updating a single Sentense entity.
type SentenseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SentenseMutation
}

// SetChinese sets the "chinese" field.
func (suo *SentenseUpdateOne) SetChinese(s string) *SentenseUpdateOne {
	suo.mutation.SetChinese(s)
	return suo
}

// SetPinyin sets the "pinyin" field.
func (suo *SentenseUpdateOne) SetPinyin(s string) *SentenseUpdateOne {
	suo.mutation.SetPinyin(s)
	return suo
}

// SetEnglish sets the "english" field.
func (suo *SentenseUpdateOne) SetEnglish(s string) *SentenseUpdateOne {
	suo.mutation.SetEnglish(s)
	return suo
}

// AddReadIDs adds the "reads" edge to the Read entity by IDs.
func (suo *SentenseUpdateOne) AddReadIDs(ids ...int) *SentenseUpdateOne {
	suo.mutation.AddReadIDs(ids...)
	return suo
}

// AddReads adds the "reads" edges to the Read entity.
func (suo *SentenseUpdateOne) AddReads(r ...*Read) *SentenseUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.AddReadIDs(ids...)
}

// Mutation returns the SentenseMutation object of the builder.
func (suo *SentenseUpdateOne) Mutation() *SentenseMutation {
	return suo.mutation
}

// ClearReads clears all "reads" edges to the Read entity.
func (suo *SentenseUpdateOne) ClearReads() *SentenseUpdateOne {
	suo.mutation.ClearReads()
	return suo
}

// RemoveReadIDs removes the "reads" edge to Read entities by IDs.
func (suo *SentenseUpdateOne) RemoveReadIDs(ids ...int) *SentenseUpdateOne {
	suo.mutation.RemoveReadIDs(ids...)
	return suo
}

// RemoveReads removes "reads" edges to Read entities.
func (suo *SentenseUpdateOne) RemoveReads(r ...*Read) *SentenseUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.RemoveReadIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SentenseUpdateOne) Select(field string, fields ...string) *SentenseUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Sentense entity.
func (suo *SentenseUpdateOne) Save(ctx context.Context) (*Sentense, error) {
	var (
		err  error
		node *Sentense
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SentenseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SentenseUpdateOne) SaveX(ctx context.Context) *Sentense {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SentenseUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SentenseUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SentenseUpdateOne) sqlSave(ctx context.Context) (_node *Sentense, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   sentense.Table,
			Columns: sentense.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: sentense.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sentense.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sentense.FieldID)
		for _, f := range fields {
			if !sentense.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sentense.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Chinese(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sentense.FieldChinese,
		})
	}
	if value, ok := suo.mutation.Pinyin(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sentense.FieldPinyin,
		})
	}
	if value, ok := suo.mutation.English(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: sentense.FieldEnglish,
		})
	}
	if suo.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sentense.ReadsTable,
			Columns: []string{sentense.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: read.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedReadsIDs(); len(nodes) > 0 && !suo.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sentense.ReadsTable,
			Columns: []string{sentense.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: read.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ReadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sentense.ReadsTable,
			Columns: []string{sentense.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: read.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Sentense{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sentense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
