// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Read is the predicate function for read builders.
type Read func(*sql.Selector)

// Sentense is the predicate function for sentense builders.
type Sentense func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
